'use client';
import ProtectedRoute from "@/components/ProtectRoute";

import React, { useEffect, useState } from 'react';
import { useAuth } from '@/lib/auth';
import AppHeader from '@/components/AppHeader';
import SidebarNav from '@/components/dashboard/SidebarNav';
import Overview from '@/components/dashboard/Overview';
import TeachersTab from '@/components/dashboard/TeachersTab';
import ChildrenTab from '@/components/dashboard/ChildrenTab';
import ParentsTab from '@/components/dashboard/ParentsTab';
import ClassesTab from '@/components/dashboard/ClassesTab';
import Schedule from "@/components/dashboard/ScheduleTab";
import Report from "@/components/dashboard/ReportTab";
import { dash } from '@/styles/dashboard';
import * as Types from '../../../shared/types/type';
import type {
  Tab,
  NewTeacherInput,
  NewChildInput,
  NewParentInput,
  NewClassInput,
} from '@/types/forms';

// Firestore (client SDK)
import { db } from '@/lib/firebase';
import { collection, addDoc, onSnapshot, query, orderBy } from 'firebase/firestore';
import swal from 'sweetalert2' // for alert library
// import { isContext } from 'vm';
import { fetchTeachers } from '@/hooks/useTeachersAPI';


export default function AdminDashboard() {
  
  const { signOutUser } = useAuth();
  const [activeTab, setActiveTab] = useState<Tab>('overview');
  const [loading, setLoading] = useState<boolean>(true);

  // --- Entity states (Teachers from Firestore; others local for now)
  const [teachers, setTeachers] = useState<Types.Teacher[]>([]);
  const [children, setChildren] = useState<Types.Child[]>([
    {
      id: '1',
      firstName: 'Emma',
      lastName: 'Wilson',
      birthDate: '2017-03-12',
      parentId: ['1'],
      classId: '1',
      enrollmentDate: '2024-09-01',
      enrollmentStatus: 'Active',
    },
    {
      id: '2',
      firstName: 'Noah',
      lastName: 'Smith',
      birthDate: '2016-11-05',
      parentId: ['2'],
      classId: '1',
      enrollmentDate: '2024-09-01',
      enrollmentStatus: 'Active',
    },
  ]);
  const [parents, setParents] = useState<Types.Parent[]>([
    {
      id: '1',
      firstName: 'Jennifer',
      lastName: 'Wilson',
      email: 'jennifer@email.com',
      role: 'parent',
      phone: '555-1234',
      passwordHash: '****',
      childIds: ['1'],
      street: '123 Main St',
      city: 'Calgary',
      province: 'AB',
      country: 'CA',
      createdAt: '2025-09-01',
    },
    {
      id: '2',
      firstName: 'Robert',
      lastName: 'Smith',
      email: 'robert@email.com',
      role: 'parent',
      phone: '555-5678',
      passwordHash: '****',
      childIds: ['2'],
      street: '45 Oak Ave',
      city: 'Calgary',
      province: 'AB',
      country: 'CA',
      createdAt: '2025-09-01',
    },
  ]);
  const [classes, setClasses] = useState<Types.Class[]>([
    { id: '1', name: 'Class 3A', locationId: 'loc-1', classroom: "Room 1", capacity: 20, volume: 20, ageStart: 7, ageEnd: 9 },
    { id: '2', name: 'Class 4B', locationId: 'loc-1', classroom: "Room 2", capacity: 20, volume: 18, ageStart: 8, ageEnd: 10 },

  ]);


  // --- Controlled form states (type-safe; no `any`)
  const [newTeacher, setNewTeacher] = useState<NewTeacherInput>({
    firstName: '',
    lastName: '',
    email: '',
    phone: '',
    address1: "",
    address2: "",
    city: "",
    province: "",
    country: "",
    postalcode: "",
    classIds: [],
    locationId: '',
    startDate: '',
    endDate: undefined,
  });

  const [newChild, setNewChild] = useState<NewChildInput>({
    firstName: '',
    lastName: '',
    birthDate: '',
    parentIdsCsv: '',
    classId: '',
    allergies: '',
    specialNeeds: '',
    subsidyStatus: '',
    enrollmentDate: '',
    enrollmentStatus: 'New',
    endDate: '',
  });

  const [newParent, setNewParent] = useState<NewParentInput>({
    firstName: '',
    lastName: '',
    email: '',
    phone: '',
    passwordHash: '',
    childIds: [],
    street: '',
    city: '',
    province: '',
    country: '',
    emergencyContact: '',
    updatedAt: '',
    preferredLanguage: '',
  });

  const [newClass, setNewClass] = useState<NewClassInput>({
    name: '',
    locationId: '',
    capacity: 0,
    volume: 0,
    ageStart: 0,
    ageEnd: 0,
    classroom: "",
  });

 // Fetching teachers
  useEffect( () => {
    setLoading(true);
    const fetchData = async () => {
    try {
      const data = await fetchTeachers();
      if (data) setTeachers(data);

      // get teachers length
      const length = data?.length ?? 0;

    } catch (err: any) {
      console.error(err);
      alert("Error fetching teachers");
    }
  };

  fetchData();
  setLoading(false);
  }, [newTeacher]); // depends on newTeacher

  // --- Actions
  const addTeacher = async () => {
    setLoading(true);
    try {
      // Persist to Firestore; id doc is generated by server
      await addDoc(collection(db, 'teachers'), {
        role: 'teacher',
        ...newTeacher, 
        endDate: newTeacher.endDate || null // 
      });
      // setTeachers([...teachers, {...newTeacher, role: "teacher", id: ""}]); this teachers should is from Firebase fetching 

      // Reset form; list updates automatically via onSnapshot
      setNewTeacher({ 
        firstName: '',
        lastName: '',
        email: '',
        phone: '',
        address1: "",
        address2: "",
        city: "",
        province: "",
        country: "",
        postalcode: "",
        classIds: [],
        locationId: '',
        startDate: '',
        endDate: undefined,
      });
      // Success Alert
      // alert(`New teacher added: ${newTeacher.firstName} ${newTeacher.lastName}`);
      swal.fire({
        icon: "success",
        title: "New Teacher",
        text: `Succefull adding new teacher: ${newTeacher.firstName} ${newTeacher.lastName}`,
        allowOutsideClick: false,
        showConfirmButton: true,
      })
    } catch (e) {
      console.error(e);
      alert('Failed to add teacher. Please try again.');
    }
    finally {
      setLoading(false);
    }
  };

  const addChild = () => {
    // Local-only example; can be migrated to Firestore with same pattern

    const child: Types.Child = {
      id: String(children.length + 1),
      firstName: newChild.firstName,
      lastName: newChild.lastName,
      birthDate: newChild.birthDate,
      parentId: newChild.parentIdsCsv
        .split(',')
        .map((s) => s.trim())
        .filter(Boolean),
      classId: newChild.classId,
      allergies: newChild.allergies || undefined,
      specialNeeds: newChild.specialNeeds || undefined,
      subsidyStatus: newChild.subsidyStatus || undefined,
      enrollmentDate: newChild.enrollmentDate,
      enrollmentStatus: newChild.enrollmentStatus,
      endDate: newChild.endDate || undefined,
    };
    setChildren((p) => [...p, child]);
    setNewChild({
      firstName: '',
      lastName: '',
      birthDate: '',
      parentIdsCsv: '',
      classId: '',
      allergies: '',
      specialNeeds: '',
      subsidyStatus: '',
      enrollmentDate: '',
      enrollmentStatus: 'New',
      endDate: '',
    });
  };


  const addParent = () => {
    // Local-only example; can be migrated to Firestore

    const parent: Types.Parent = {
      id: String(parents.length + 1),
      role: 'parent',
      createdAt: new Date().toISOString(),
      ...newParent,
    };
    setParents((p) => [...p, parent]);

    setNewParent({
      firstName: '',
      lastName: '',
      email: '',
      phone: '',
      passwordHash: '',
      childIds: [],
      street: '',
      city: '',
      province: '',
      country: '',
      emergencyContact: '',
      updatedAt: '',
      preferredLanguage: '',
    });
  };


  const addClass = () => {
    // Local-only example; can be migrated to Firestore
    const cls: Types.Class = { id: String(classes.length + 1), ...newClass };
    setClasses((p) => [...p, cls]);
    setNewClass({
      name: '',
      locationId: '',
      capacity: 0,
      volume: 0,
      ageStart: 0,
      ageEnd: 0,
      classroom: "",
    });

  };


  if (loading) return <ProtectedRoute><div> Loading </div></ProtectedRoute>
  else {
    return (
    // Protected route for admin
    <ProtectedRoute>

    <div style={dash.container}>
      <header style={dash.header}>
        <AppHeader />
        <h1 style={dash.headerTitle}>Admin Dashboard</h1>
        <div style={dash.headerActions}>
          <span style={dash.welcome}>Welcome, Admin</span>
          <button onClick={signOutUser} style={dash.logoutButton}>
            Logout
          </button>
        </div>
      </header>

      <div style={dash.content}>
        <SidebarNav active={activeTab} onChange={setActiveTab} />
        <main style={dash.main}>
          {activeTab === 'overview' && (
            <Overview
              teacherCount={teachers.length}
              childCount={children.length}
              parentCount={parents.length}
              classCount={classes.length}
            />
          )}

          {activeTab === 'teachers' && (
            <TeachersTab
              teachers={teachers}
              newTeacher={newTeacher}
              setNewTeacher={setNewTeacher}
              onAdd={addTeacher}
            />

         
          )}

          {activeTab === 'children' && (
            <ChildrenTab
              classes={classes}
              parents={parents}
              childList={children} // avoid reserved prop "children"
              newChild={newChild}
              setNewChild={setNewChild}
              onAdd={addChild}
            />
          )}

          {activeTab === 'parents' && (
            <ParentsTab
              parents={parents}
              newParent={newParent}
              setNewParent={setNewParent}
              onAdd={addParent}
            />
          )}

          {activeTab === 'classes' && (
            <ClassesTab
              classes={classes}
              teachers={teachers}
              newClass={newClass}
              setNewClass={setNewClass}
              onAdd={addClass}
            />
          )}

          {activeTab === 'schedule' && (
             <ClassesTab
              classes={classes}
              teachers={teachers}
              newClass={newClass}
              setNewClass={setNewClass}
              onAdd={addClass}
            />
          )}

          {activeTab === 'report' && (
            <ClassesTab
              classes={classes}
              teachers={teachers}
              newClass={newClass}
              setNewClass={setNewClass}
              onAdd={addClass}
            />
          )}
        </main>
      </div>
    </div>
    </ProtectedRoute>
  );
  }
}
