/**
 * AI-Generated Code Citation
 * Generated by: Claude Code (Anthropic)
 * Prompt: "Modernize TeachersTab with email-first card layout, address autocomplete, and refined visual hierarchy"
 * Date: 2025-09-30
 */

"use client";

import * as Types from "../../../shared/types/type";
import { useCallback, useState, useEffect, useRef } from "react";
import type { NewTeacherInput } from "@/types/forms";
import AutoCompleteAddress, { Address } from "@/components/AutoCompleteAddress";
import api from "@/api/client";
import { ENDPOINTS } from "@/api/endpoint";
import {fetchLocationsLite, type LocationLite } from "@/services/useLocationsAPI";
import { data } from "react-router-dom";

export default function TeachersTab({
  teachers,
  newTeacher,
  setNewTeacher,
  onAdd,
  locations,
}: {
  teachers: Types.Teacher[];
  newTeacher: NewTeacherInput;
  setNewTeacher: React.Dispatch<React.SetStateAction<NewTeacherInput>>;
  onAdd: () => void;
  locations: LocationLite[];
}) {
  const [isFormOpen, setIsFormOpen] = useState(false);
  const [searchTerm, setSearchTerm] = useState("");
  const [currentPage, setCurrentPage] = useState(1);
  const [editingTeacher, setEditingTeacher] = useState<Types.Teacher | null>(null);
  const [showAssignClass, setShowAssignClass] = useState<string | null>(null);
  const [selectedClass, setSelectedClass] = useState('');
  const [isDraftRestored, setIsDraftRestored] = useState(false);
  const saveTimeoutRef = useRef<NodeJS.Timeout | null>(null);


  // Allow Teachers of different Locations 
  const getLocationLabel = (locId?: string) => {
    if (!locId) return "—";
    const found = (locations ?? []).find((l) => l.id === locId);
    return found?.name || locId;
  };

  // Restore draft when form opens
  useEffect(() => {
    if (isFormOpen && !editingTeacher) {
      const draft = sessionStorage.getItem('teacher-form-draft');
      if (draft) {
        try {
          const parsed = JSON.parse(draft);
          setNewTeacher(parsed);
          setIsDraftRestored(true);
        } catch (e) {
          console.error('Failed to restore draft:', e);
        }
      }
    }
  }, [isFormOpen, editingTeacher, setNewTeacher]);

  // Helper to update form and save draft
  const updateTeacher = useCallback((updates: Partial<NewTeacherInput>) => {
    setNewTeacher(prev => {
      const updated = { ...prev, ...updates };

      // Save to sessionStorage with debounce
      if (!editingTeacher) {
        if (saveTimeoutRef.current) {
          clearTimeout(saveTimeoutRef.current);
        }
        saveTimeoutRef.current = setTimeout(() => {
          sessionStorage.setItem('teacher-form-draft', JSON.stringify(updated));
        }, 500);
      }

      return updated;
    });
  }, [editingTeacher, setNewTeacher]);

  // Clear draft
  const clearDraft = useCallback(() => {
    sessionStorage.removeItem('teacher-form-draft');
    setIsDraftRestored(false);
  }, []);

  const handleAddressChange = useCallback((a: Address) => {
    updateTeacher({
      address1: a.address1,
      address2: a.address2,
      city: a.city,
      province: a.province,
      country: a.country,
      postalcode: a.postalcode
    });
  }, [updateTeacher]);

  // Filter teachers based on search
  const filteredTeachers = teachers.filter(t =>
    t.firstName.toLowerCase().includes(searchTerm.toLowerCase()) ||
    t.lastName.toLowerCase().includes(searchTerm.toLowerCase()) ||
    t.email.toLowerCase().includes(searchTerm.toLowerCase())
  );

  const teachersPerPage = 6;
  const totalPages = Math.ceil(filteredTeachers.length / teachersPerPage) || 1;
  const startIndex = (currentPage - 1) * teachersPerPage;
  const paginatedTeachers = filteredTeachers.slice(startIndex, startIndex + teachersPerPage);

  // After done editing current Teacher or adding New Teacher
  const handleFormSubmit = (e: React.FormEvent) => {
    e.preventDefault();
    if (editingTeacher) {
      console.log('Update teacher:', { ...editingTeacher, ...newTeacher });

      // Find the only info that is updating: currently (editingTeacher) => new (newTeacher)      
      // Case: no changes, do nothing
      if (JSON.stringify(newTeacher) === JSON.stringify(editingTeacher)) return;

      // Else, collect only changed fileds; is type Parital<Types.Teacher> with Teacher ID
      const teacherId = editingTeacher.id;
      const newInfo = Object.fromEntries((Object.keys(newTeacher) as (keyof NewTeacherInput)[])
        .filter((key) => newTeacher[key] !== editingTeacher[key])
        .map((key) => [key, newTeacher[key]])
      ) as Partial<NewTeacherInput>;

      // Call onUpdate();
      onUpdate(teacherId, newInfo);


      // After upating Teacher new Info
      setEditingTeacher(null);
      // Reset form to empty state
      setNewTeacher({
        firstName: "",
        lastName: "",
        email: "",
        phone: "",
        address1: "",
        address2: "",
        city: "",
        province: "",
        country: "",
        postalcode: "",
        startDate: "",
        endDate: undefined,
      });
    } else {
      onAdd();
    }
    clearDraft(); // Clear draft after successful submission
    setIsFormOpen(false);
  };

  const handleAddClick = () => {
    setEditingTeacher(null);
    setNewTeacher({
      firstName: "",
      lastName: "",
      email: "",
      phone: "",
      address1: "",
      address2: "",
      city: "",
      province: "",
      country: "",
      postalcode: "",
      startDate: "",
      endDate: undefined,
      status: Types.TeacherStatus.New,
      isRegistered: false,
    });
  };

  const handleFormSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    if (editingTeacher) {
      const id = editingTeacher.id;
      const updated = await api.put<Types.Teacher>(`${ENDPOINTS.teachers}/${id}`, { ...newTeacher });
      setRows((prev) => prev.map((t) => (t.id === id ? { ...t, ...updated } : t)));
      setEditingTeacher(null);
      resetForm();
      setIsFormOpen(false);
      return;
    } else {
      onAdd();
      setIsFormOpen(false);
    }
    await onAdd();
    setIsFormOpen(false);
  };

  const handleAddClick = () => {
    setEditingTeacher(null);
    resetForm();
    setIsFormOpen(true);
  };


  // Opening form, and allow editing
  const handleEditClick = (teacher: Types.Teacher) => {
    // Set editing teacher is passing Teacher
    setEditingTeacher(teacher);

    // Loading input field with current value of editing teacher
    setNewTeacher({
      firstName: teacher.firstName,
      lastName: teacher.lastName,
      locationId: teacher.locationId,
      email: teacher.email,
      phone: teacher.phone,
      address1: teacher.address1,
      address2: teacher.address2,
      city: teacher.city,
      province: teacher.province,
      country: teacher.country,
      postalcode: teacher.postalcode,
      startDate: String(teacher.startDate || ""),
      endDate: teacher.endDate ? String(teacher.endDate) : undefined,
      status: teacher.status,
      isRegistered: teacher.isRegistered,
    });
    setIsFormOpen(true);
  };

  const handleDeleteClick = (teacher: Types.Teacher) => {
    if (window.confirm(`Are you sure you want to delete ${teacher.firstName} ${teacher.lastName}?`)) {
      console.log('Delete teacher:', teacher.id);
      // Calling onDelete()
      onDelete(teacher.id);
    }
    // else, cancel
    else return 
  };

  const handleAssignClass = (teacherId: string) => {
    setShowAssignClass(teacherId);
    setSelectedClass("");
  };

  const handleSaveClass = async () => {
    if (!showAssignClass || !selectedClass) return;
    const id = showAssignClass;

    await api.post<{ ok: boolean }>(
      `${ENDPOINTS.teachers}/${id}/assign`,
      { classId: selectedClass }
    );

    setRows(prev =>
      prev.map((t) => (t.id === id ? { ...t, classId: selectedClass } : t))
    );
    setShowAssignClass(null);
    setSelectedClass("");
  };

  const formatAddress = (teacher: Types.Teacher) => {
    const parts = [
      teacher.address2,
      teacher.address1,
      teacher.city,
      teacher.province,
      teacher.country,
      teacher.postalcode,
    ].filter(Boolean) as string[];
    return parts.join(", ");
  };

  return (
    <div className="p-6 bg-gray-50 min-h-screen">
      <div className="mb-6">
        <div className="flex justify-between items-center mb-4">
          <h2 className="text-3xl font-bold text-gray-800">Teachers</h2>
          <button
            onClick={handleAddClick}
            className="bg-gray-700 hover:bg-gray-800 text-white font-medium px-4 py-2 rounded-lg transition duration-200 flex items-center gap-2 text-sm shadow-sm"
          >
            <span className="text-lg">+</span> Add Teacher
          </button>
        </div>
        <div className="flex items-center gap-3 mb-4">
          <div className="flex-1 relative">
            <input
              type="text"
              placeholder="Search by name or email..."
              value={searchTerm}
              onChange={(e) => {
                setSearchTerm(e.target.value);
                setCurrentPage(1);
              }}
              className="w-full px-4 py-2 bg-white border border-gray-300 rounded-lg focus:outline-none focus:ring-1 focus:ring-gray-300 focus:border-gray-400"
            />
            {searchTerm && (
              <button
                onClick={() => {
                  setSearchTerm("");
                  setCurrentPage(1);
                }}
                className="absolute right-3 top-1/2 -translate-y-1/2 text-gray-400 hover:text-gray-600"
              >
                ✕
              </button>
            )}
          </div>
          <div className="text-gray-500 text-xs whitespace-nowrap">
            {filteredTeachers.length} of {rows.length}
          </div>
        </div>
      </div>

      {paginatedTeachers.length > 0 ? (
        <div className="grid grid-cols-1 lg:grid-cols-2 gap-5 mb-8">
          {paginatedTeachers.map((teacher) => (
            <div key={teacher.id} className="bg-white rounded-xl shadow-sm hover:shadow-md transition-shadow duration-200 p-5">
              <div className="mb-4">
                <div className="flex items-baseline gap-2 mb-1">
                  <h3 className="text-xl font-bold text-gray-900 truncate">{teacher.email}</h3>
                </div>
                <div className="flex items-center gap-3">
                  <span className="text-sm text-gray-500">{teacher.firstName} {teacher.lastName}</span>
                  <span className="text-gray-300">•</span>
                  <span className="text-sm font-medium text-gray-700">{teacher.phone}</span>
                </div>
              </div>
              <div className="flex items-center gap-2 text-gray-700 text-sm">
                    <span>📍</span>
                    <span className="truncate">{getLocationLabel(teacher.locationId)}</span>
              </div>
              <div className="space-y-2 mb-4 pb-4 border-b border-gray-100">
                <div className="text-xs text-gray-500 leading-relaxed"> <span>🏠</span> {formatAddress(teacher)}</div>
                <div className="text-xs text-gray-400">
                  <div>Status: {teacher.status}</div>
                  {String(teacher.startDate)}{teacher.endDate ? ` → ${String(teacher.endDate)}` : " → Present"}
                </div>
              </div>
              <div className="flex gap-2">
                <button
                  onClick={() => handleAssignClass(teacher.id)}
                  className="flex-1 bg-white/60 backdrop-blur-sm border border-gray-200 hover:bg-white/80 hover:border-gray-300 text-gray-700 font-medium px-3 py-2 rounded-lg transition-all duration-200 text-xs shadow-sm"
                >
                  Assign
                </button>
                <button
                  onClick={() => handleEditClick(teacher)}
                  className="flex-1 bg-white/60 backdrop-blur-sm border border-gray-200 hover:bg-white/80 hover:border-gray-300 text-gray-700 font-medium px-3 py-2 rounded-lg transition-all duration-200 text-xs shadow-sm"
                >
                  Edit
                </button>
                <button
                  onClick={() => handleDeleteClick(teacher)}
                  className="flex-1 bg-white/60 backdrop-blur-sm border border-gray-200 hover:bg-white/80 hover:border-red-300 text-gray-700 hover:text-red-600 font-medium px-3 py-2 rounded-lg transition-all duration-200 text-xs shadow-sm"
                >
                  Delete
                </button>
              </div>
            </div>
          ))}
        </div>
      ) : (
        <div className="bg-white rounded-lg shadow-md p-12 text-center">
          <div className="text-gray-400 text-6xl mb-4">👥</div>
          <h3 className="text-xl font-semibold text-gray-600 mb-2">No teachers found</h3>
          <p className="text-gray-500">{searchTerm ? "Try adjusting your search terms" : "Get started by adding your first teacher"}</p>
        </div>
      )}

      {totalPages > 1 && (
        <div className="flex justify-center items-center gap-2">
          <button
            onClick={() => setCurrentPage((prev) => Math.max(1, prev - 1))}
            disabled={currentPage === 1}
            className={`px-4 py-2 rounded-lg font-medium transition duration-200 ${currentPage === 1 ? "bg-gray-200 text-gray-400 cursor-not-allowed" : "bg-white text-gray-700 hover:bg-gray-100 shadow-sm"}`}
          >
            ← Previous
          </button>
          <div className="flex gap-2">
            {Array.from({ length: totalPages }, (_, i) => i + 1).map((page) => (
              <button
                key={page}
                onClick={() => setCurrentPage(page)}
                className={`w-10 h-10 rounded-lg font-medium transition duration-200 ${currentPage === page ? "bg-blue-600 text-white" : "bg-white text-gray-700 hover:bg-gray-100 shadow-sm"}`}
              >
                {page}
              </button>
            ))}
          </div>
          <button
            onClick={() => setCurrentPage((prev) => Math.min(totalPages, prev + 1))}
            disabled={currentPage === totalPages}
            className={`px-4 py-2 rounded-lg font-medium transition duration-200 ${currentPage === totalPages ? "bg-gray-200 text-gray-400 cursor-not-allowed" : "bg-white text-gray-700 hover:bg-gray-100 shadow-sm"}`}
          >
            Next →
          </button>
        </div>
      )}

      {isFormOpen && (
        <div
          className="fixed inset-0 bg-white/30 backdrop-blur-md flex items-center justify-center p-4 z-50"
          onClick={() => {
            setIsFormOpen(false);
            setEditingTeacher(null);
          }}
        >
          <div
            className="bg-white rounded-xl shadow-2xl max-w-2xl w-full max-h-[90vh] overflow-y-auto border border-gray-100"
            onClick={(e) => e.stopPropagation()}
          >
            <div className="sticky top-0 bg-white border-b border-gray-200 px-6 py-4 flex justify-between items-center">
              <div>
                <h3 className="text-2xl font-bold text-gray-800">
                  {editingTeacher ? 'Edit Teacher' : 'Add New Teacher'}
                </h3>
                {isDraftRestored && !editingTeacher && (
                  <p className="text-xs text-green-600 mt-1">✓ Draft restored</p>
                )}
              </div>
              <button
                onClick={() => {
                  setIsFormOpen(false);
                  setEditingTeacher(null);
                }}
                className="text-gray-400 hover:text-gray-600 text-2xl"
              >
                ✕
              </button>
            </div>

            <form onSubmit={handleFormSubmit} className="p-6">
              <div className="space-y-4">
                <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                  <label className="block">
                    <span className="text-gray-700 font-medium mb-1 block">First Name *</span>
                    <input
                      type="text"
                      className="w-full px-4 py-2 border border-gray-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-blue-500"
                      placeholder="First Name"
                      value={newTeacher.firstName}
                      onChange={(e) => updateTeacher({firstName: e.target.value })}
                      required
                    />
                  </label>
                  <label className="block">
                    <span className="text-gray-700 font-medium mb-1 block">Last Name *</span>
                    <input
                      type="text"
                      className="w-full px-4 py-2 border border-gray-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-blue-500"
                      placeholder="Last Name"
                      value={newTeacher.lastName}
                      onChange={(e) => updateTeacher({lastName: e.target.value })}
                      required
                    />
                  </label>
                </div>

                <label className="block">
                  <span className="text-gray-700 font-medium mb-1 block">Location *</span>
                  <select
                    className="w-full px-4 py-2 border border-gray-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-purple-500"
                    value={newTeacher.locationId}
                    onChange={(e) => updateTeacher({locationId: e.target.value })}
                    required
                    disabled={(locations ?? []).length <= 1} // disable if single
                  >
                    {(locations ?? []).length > 1 && (
                      <option value="" disabled>Select a location</option>
                    )}
                    {(locations ?? []).map(l => (
                      <option key={l.id} value={l.id}>{l.name || l.id}</option>
                    ))}
                  </select>
                </label>

                <label className="block">
                  <span className="text-gray-700 font-medium mb-1 block">Email *</span>
                  <input
                    type="email"
                    className="w-full px-4 py-2 border border-gray-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-blue-500"
                    placeholder="Email"
                    value={newTeacher.email}
                    onChange={(e) => updateTeacher({email: e.target.value })}
                    required
                  />
                </label>

                <label className="block">
                  <span className="text-gray-700 font-medium mb-1 block">Phone Number *</span>
                  <input
                    className="w-full px-4 py-2 border border-gray-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-blue-500"
                    placeholder="e.g. 403 111 2284"
                    value={newTeacher.phone}
                    onChange={(e) => updateTeacher({phone: e.target.value })}
                    required
                  />
                </label>

                <div className="block">
                  <span className="text-gray-700 font-medium mb-1 block">Address *</span>
                  <AutoCompleteAdress 
                  addressValues={newTeacherAddressValues}
                  onAddressChanged={handleAddressChange} 
                  />
                </div>

                <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                  <label className="block">
                    <span className="text-gray-700 font-medium mb-1 block">Start Date *</span>
                    <input
                      type="date"
                      className="w-full px-4 py-2 border border-gray-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-blue-500"
                      value={newTeacher.startDate}
                      onChange={(e) => updateTeacher({startDate: e.target.value })}
                      required
                    />
                  </label>
                  <label className="block">
                    <span className="text-gray-700 font-medium mb-1 block">End Date</span>
                    <input
                      type="date"
                      className="w-full px-4 py-2 border border-gray-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-blue-500"
                      placeholder="End Date (optional)"
                      value={newTeacher.endDate || ""}
                      onChange={(e) => updateTeacher({endDate: e.target.value || undefined })}
                    />
                  </label>
                </div>
              </div>

              <div className="flex gap-3 mt-6 pt-6 border-t border-gray-200">
                <button
                  type="button"
                  onClick={() => {
                    setIsFormOpen(false);
                    setEditingTeacher(null);
                  }}
                  className="flex-1 bg-gray-200 hover:bg-gray-300 text-gray-700 font-medium px-6 py-3 rounded-lg transition duration-200"
                >
                  Cancel
                </button>
                {!editingTeacher && (
                  <button
                    type="button"
                    onClick={clearDraft}
                    className="bg-gray-100 hover:bg-gray-200 text-gray-600 font-medium px-6 py-3 rounded-lg transition duration-200 text-sm"
                  >
                    Clear Draft
                  </button>
                )}
                <button
                  type="submit"
                  className="flex-1 bg-blue-600 hover:bg-blue-700 text-white font-medium px-6 py-3 rounded-lg transition duration-200"
                >
                  {editingTeacher ? "Update Teacher" : "Add Teacher"}
                </button>
              </div>
            </form>
          </div>
        </div>
      )}

      {showAssignClass && (
        <div
          className="fixed inset-0 bg-white/30 backdrop-blur-md flex items-center justify-center p-4 z-50"
          onClick={() => {
            setShowAssignClass(null);
            setSelectedClass("");
          }}
        >
          <div
            className="bg-white rounded-xl shadow-2xl max-w-md w-full border border-gray-100"
            onClick={(e) => e.stopPropagation()}
          >
            <div className="border-b border-gray-200 px-6 py-4 flex justify-between items-center">
              <h3 className="text-xl font-bold text-gray-800">Assign Class</h3>
              <button
                onClick={() => {
                  setShowAssignClass(null);
                  setSelectedClass("");
                }}
                className="text-gray-400 hover:text-gray-600 text-2xl"
              >
                ✕
              </button>
            </div>

            <div className="p-6">
              <label className="block mb-4">
                <span className="text-gray-700 font-medium mb-2 block">Select Class</span>
                <select
                  value={selectedClass}
                  onChange={(e) => setSelectedClass(e.target.value)}
                  className="w-full px-4 py-2 border border-gray-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-blue-500"
                >
                  <option value="">-- Select a class --</option>
                  <option value="class1">Class 1 (Placeholder)</option>
                  <option value="class2">Class 2 (Placeholder)</option>
                  <option value="class3">Class 3 (Placeholder)</option>
                </select>
              </label>

              <div className="flex gap-3">
                <button
                  onClick={() => {
                    setShowAssignClass(null);
                    setSelectedClass("");
                  }}
                  className="flex-1 bg-gray-200 hover:bg-gray-300 text-gray-700 font-medium px-6 py-3 rounded-lg transition duration-200"
                >
                  Cancel
                </button>
                <button
                  onClick={handleSaveClass}
                  className="flex-1 bg-green-600 hover:bg-green-700 text-white font-medium px-6 py-3 rounded-lg transition duration-200"
                >
                  Save
                </button>
              </div>
            </div>
          </div>
        </div>
      )}
    </div>
  );
}
