/**
 * Teacher Calendar Tab
 *
 * Generated by: Claude Opus 4.1 (claude-opus-4-1-20250805)
 * Date: October 2024
 *
 * PROMPT USED:
 * "Create a React Native calendar for a daycare teacher app with:
 * 1. Month view with event dots
 * 2. Daily schedule section showing activities
 * 3. Event categories: Activities, Birthdays, Meetings, Holidays
 * 4. Gradient background matching the app theme
 * 5. Card-based event display with time and details
 * Make it modern and functional for daycare management."
 */

import {
  View,
  Text,
  ScrollView,
  StyleSheet,
  Pressable,
  FlatList,
} from "react-native";
import { useState, useMemo } from "react";
import { LinearGradient } from "expo-linear-gradient";
import { useSafeAreaInsets } from "react-native-safe-area-context";
import {
  ChevronLeft,
  ChevronRight,
  Calendar as CalendarIcon,
  Cake,
  Users,
  Star,
  Clock,
  MapPin,
  Baby,
  School,
  AlertCircle,
} from "lucide-react-native";
import { mockDaycareEvents } from "../../../src/data/mockData";

import { EventType } from "../../../../shared/types/type";

type Event = {
  id: string;
  title: string;
  time?: string;
  location?: string;
  type: EventType;
  description?: string;
  children?: string[];
};

type DayEvents = {
  [date: string]: Event[];
};

const eventColors = {
  dailyActivity: { bg: "#DCFCE7", color: "#16A34A", icon: School }, // FROM DASHBOARD, happend every weekdays except holidays
  childActivity: { bg: "#E0F2FE", color: "#0EA5E9", icon: Star }, // FROM DASHBOARD, special activities for children, happend occasionally
  meeting: { bg: "#F3E8FF", color: "#9333EA", icon: Users }, // FROM DASHBOARD - teacher and taff meetings. (applied for all classes with details)

  holiday: { bg: "#FEF3C7", color: "#F59E0B", icon: CalendarIcon }, // AUTO-computed based on public holidays
  birthday: { bg: "#FCE7F3", color: "#EC4899", icon: Cake }, // AUTO- computed based on children's birthdates
};

export default function TeacherCalendar() {
  const insets = useSafeAreaInsets();
  const [selectedDate, setSelectedDate] = useState(new Date());
  const [currentMonth, setCurrentMonth] = useState(new Date());

  // Get calendar days for current month
  const calendarDays = useMemo(() => {
    const year = currentMonth.getFullYear();
    const month = currentMonth.getMonth();
    const firstDay = new Date(year, month, 1);
    const lastDay = new Date(year, month + 1, 0);
    const startDate = new Date(firstDay);
    startDate.setDate(startDate.getDate() - firstDay.getDay());

    const days = [];
    const current = new Date(startDate);

    for (let i = 0; i < 42; i++) {
      days.push(new Date(current));
      current.setDate(current.getDate() + 1);
      if (i >= 35 && current.getMonth() !== month) break;
    }

    return days;
  }, [currentMonth]);

  // Format date for event lookup
  const formatDateKey = (date: Date) => {
    return `${date.getFullYear()}-${String(date.getMonth() + 1).padStart(
      2,
      "0"
    )}-${String(date.getDate()).padStart(2, "0")}`;
  };

  // Get events for selected date
  const selectedDateEvents = mockDaycareEvents[formatDateKey(selectedDate) as keyof typeof mockDaycareEvents] || [];

  // Navigate months
  const goToPreviousMonth = () => {
    setCurrentMonth(
      new Date(currentMonth.getFullYear(), currentMonth.getMonth() - 1)
    );
  };

  const goToNextMonth = () => {
    setCurrentMonth(
      new Date(currentMonth.getFullYear(), currentMonth.getMonth() + 1)
    );
  };

  const goToToday = () => {
    const today = new Date();
    setCurrentMonth(today);
    setSelectedDate(today);
  };

  const monthNames = [
    "January", "February", "March", "April", "May", "June",
    "July", "August", "September", "October", "November", "December"
  ];

  const dayNames = ["S", "M", "T", "W", "T", "F", "S"];

  const renderEvent = (event: Event) => {
    const config = eventColors[event.type];
    const IconComponent = config.icon;

    return (
      <Pressable
        key={event.id}
        style={({ pressed }) => [
          styles.eventCard,
          { transform: [{ scale: pressed ? 0.98 : 1 }] },
        ]}
      >
        <View
          style={[styles.eventIconContainer, { backgroundColor: config.bg }]}
        >
          <IconComponent size={20} color={config.color} strokeWidth={2} />
        </View>
        <View style={styles.eventContent}>
          <Text style={styles.eventTitle}>{event.title}</Text>
          <View style={styles.eventDetails}>
            {event.time && (
              <View style={styles.eventDetailRow}>
                <Clock size={12} color="#64748B" />
                <Text style={styles.eventDetailText}>{event.time}</Text>
              </View>
            )}
            {event.location && (
              <View style={styles.eventDetailRow}>
                <MapPin size={12} color="#64748B" />
                <Text style={styles.eventDetailText}>{event.location}</Text>
              </View>
            )}
            {event.children && (
              <View style={styles.eventDetailRow}>
                <Baby size={12} color="#64748B" />
                <Text style={styles.eventDetailText}>
                  {event.children.join(", ")}
                </Text>
              </View>
            )}
          </View>
          {event.description && (
            <Text style={styles.eventDescription}>{event.description}</Text>
          )}
        </View>
      </Pressable>
    );
  };

  return (
    <View style={styles.container}>
      {/* Gradient Background */}
      <LinearGradient
        colors={["#E0E7FF", "#F0F4FF", "#FFFFFF"]}
        style={styles.gradientBackground}
      />

      <ScrollView
        style={styles.scrollView}
        showsVerticalScrollIndicator={false}
      >
        {/* Header */}
        <View style={[styles.header, { paddingTop: insets.top + 20 }]}>
          <Text style={styles.title}>Calendar</Text>
          <Pressable style={styles.todayButton} onPress={goToToday}>
            <Text style={styles.todayButtonText}>Today</Text>
          </Pressable>
        </View>

        {/* Month Navigation */}
        <View style={styles.monthNav}>
          <Pressable onPress={goToPreviousMonth} style={styles.navButton}>
            <ChevronLeft size={24} color="#475569" />
          </Pressable>
          <Text style={styles.monthTitle}>
            {monthNames[currentMonth.getMonth()]} {currentMonth.getFullYear()}
          </Text>
          <Pressable onPress={goToNextMonth} style={styles.navButton}>
            <ChevronRight size={24} color="#475569" />
          </Pressable>
        </View>

        {/* Calendar Grid */}
        <View style={styles.calendarContainer}>
          {/* Day Names */}
          <View style={styles.dayNamesRow}>
            {dayNames.map((day, index) => (
              <View key={index} style={styles.dayNameCell}>
                <Text style={styles.dayNameText}>{day}</Text>
              </View>
            ))}
          </View>

          {/* Calendar Days */}
          <View style={styles.calendarGrid}>
            {calendarDays.map((date, index) => {
              const isCurrentMonth =
                date.getMonth() === currentMonth.getMonth();
              const isToday =
                date.toDateString() === new Date().toDateString();
              const isSelected =
                date.toDateString() === selectedDate.toDateString();
              const dateKey = formatDateKey(date);
              const hasEvents = mockDaycareEvents[dateKey as keyof typeof mockDaycareEvents]?.length > 0;

              return (
                <Pressable
                  key={index}
                  style={[
                    styles.dayCell,
                    isSelected && styles.selectedDayCell,
                    isToday && styles.todayCell,
                  ]}
                  onPress={() => setSelectedDate(date)}
                >
                  <Text
                    style={[
                      styles.dayText,
                      !isCurrentMonth && styles.otherMonthText,
                      isSelected && styles.selectedDayText,
                      isToday && styles.todayText,
                    ]}
                  >
                    {date.getDate()}
                  </Text>
                  {hasEvents && (
                    <View style={styles.eventDotsContainer}>
                      {mockDaycareEvents[dateKey as keyof typeof mockDaycareEvents].slice(0, 3).map((event, i) => (
                        <View
                          key={i}
                          style={[
                            styles.eventDot,
                            { backgroundColor: eventColors[event.type as keyof typeof eventColors].color },
                          ]}
                        />
                      ))}
                    </View>
                  )}
                </Pressable>
              );
            })}
          </View>
        </View>

        {/* Selected Date Events */}
        <View style={styles.eventsSection}>
          <Text style={styles.eventsSectionTitle}>
            {selectedDate.toLocaleDateString("en-US", {
              weekday: "long",
              month: "long",
              day: "numeric",
            })}
          </Text>

          {selectedDateEvents.length > 0 ? (
            <View style={styles.eventsList}>
              {selectedDateEvents.map(renderEvent as any)}
            </View>
          ) : (
            <View style={styles.noEventsContainer}>
              <CalendarIcon size={48} color="#CBD5E1" strokeWidth={1.5} />
              <Text style={styles.noEventsText}>No events scheduled</Text>
              <Text style={styles.noEventsSubtext}>
                Tap + to add an event for this day
              </Text>
            </View>
          )}
        </View>

        {/* Quick Stats */}
        <View style={styles.statsContainer}>
          <Text style={styles.statsTitle}>This Week</Text>
          <View style={styles.statsGrid}>
            <View style={[styles.statCard, { backgroundColor: "#F0F9FF" }]}>
              <Text style={styles.statNumber}>3</Text>
              <Text style={styles.statLabel}>Activities</Text>
            </View>
            <View style={[styles.statCard, { backgroundColor: "#FFF0F6" }]}>
              <Text style={styles.statNumber}>2</Text>
              <Text style={styles.statLabel}>Birthdays</Text>
            </View>
            <View style={[styles.statCard, { backgroundColor: "#F5F3FF" }]}>
              <Text style={styles.statNumber}>1</Text>
              <Text style={styles.statLabel}>Meeting</Text>
            </View>
          </View>
        </View>
      </ScrollView>
    </View>
  );
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#FFFFFF",
  },
  gradientBackground: {
    position: "absolute",
    top: 0,
    left: 0,
    right: 0,
    height: 400,
  },
  scrollView: {
    flex: 1,
  },
  header: {
    paddingHorizontal: 20,
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 20,
  },
  title: {
    fontSize: 32,
    fontWeight: "bold",
    color: "#1E293B",
    letterSpacing: -0.5,
  },
  todayButton: {
    backgroundColor: "#6366F1",
    paddingHorizontal: 16,
    paddingVertical: 8,
    borderRadius: 20,
  },
  todayButtonText: {
    color: "#FFFFFF",
    fontSize: 14,
    fontWeight: "600",
  },
  monthNav: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: 20,
    marginBottom: 20,
  },
  navButton: {
    padding: 8,
  },
  monthTitle: {
    fontSize: 20,
    fontWeight: "600",
    color: "#1E293B",
  },
  calendarContainer: {
    marginHorizontal: 20,
    backgroundColor: "rgba(255, 255, 255, 0.9)",
    borderRadius: 20,
    padding: 16,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.05,
    shadowRadius: 8,
    elevation: 2,
    marginBottom: 24,
  },
  dayNamesRow: {
    flexDirection: "row",
    marginBottom: 8,
  },
  dayNameCell: {
    flex: 1,
    alignItems: "center",
  },
  dayNameText: {
    fontSize: 12,
    fontWeight: "600",
    color: "#64748B",
  },
  calendarGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
  },
  dayCell: {
    width: "14.28%",
    aspectRatio: 1,
    alignItems: "center",
    justifyContent: "center",
    padding: 4,
  },
  selectedDayCell: {
    backgroundColor: "#6366F1",
    borderRadius: 12,
  },
  todayCell: {
    backgroundColor: "#E0E7FF",
    borderRadius: 12,
  },
  dayText: {
    fontSize: 15,
    color: "#1E293B",
  },
  otherMonthText: {
    color: "#CBD5E1",
  },
  selectedDayText: {
    color: "#FFFFFF",
    fontWeight: "600",
  },
  todayText: {
    fontWeight: "600",
  },
  eventDotsContainer: {
    flexDirection: "row",
    position: "absolute",
    bottom: 2,
    gap: 2,
  },
  eventDot: {
    width: 4,
    height: 4,
    borderRadius: 2,
  },
  eventsSection: {
    paddingHorizontal: 20,
    marginBottom: 24,
  },
  eventsSectionTitle: {
    fontSize: 18,
    fontWeight: "600",
    color: "#1E293B",
    marginBottom: 16,
  },
  eventsList: {
    gap: 12,
  },
  eventCard: {
    flexDirection: "row",
    backgroundColor: "rgba(255, 255, 255, 0.9)",
    borderRadius: 16,
    padding: 16,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.05,
    shadowRadius: 8,
    elevation: 2,
    marginBottom: 12,
  },
  eventIconContainer: {
    width: 40,
    height: 40,
    borderRadius: 12,
    alignItems: "center",
    justifyContent: "center",
    marginRight: 12,
  },
  eventContent: {
    flex: 1,
  },
  eventTitle: {
    fontSize: 16,
    fontWeight: "600",
    color: "#1E293B",
    marginBottom: 4,
  },
  eventDetails: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 12,
    marginTop: 4,
  },
  eventDetailRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
  },
  eventDetailText: {
    fontSize: 12,
    color: "#64748B",
  },
  eventDescription: {
    fontSize: 13,
    color: "#64748B",
    marginTop: 6,
    fontStyle: "italic",
  },
  noEventsContainer: {
    alignItems: "center",
    paddingVertical: 40,
    backgroundColor: "rgba(255, 255, 255, 0.7)",
    borderRadius: 16,
  },
  noEventsText: {
    fontSize: 16,
    color: "#64748B",
    marginTop: 12,
    fontWeight: "500",
  },
  noEventsSubtext: {
    fontSize: 14,
    color: "#94A3B8",
    marginTop: 4,
  },
  statsContainer: {
    paddingHorizontal: 20,
    marginBottom: 40,
  },
  statsTitle: {
    fontSize: 18,
    fontWeight: "600",
    color: "#1E293B",
    marginBottom: 12,
  },
  statsGrid: {
    flexDirection: "row",
    gap: 12,
  },
  statCard: {
    flex: 1,
    padding: 16,
    borderRadius: 16,
    alignItems: "center",
  },
  statNumber: {
    fontSize: 24,
    fontWeight: "700",
    color: "#1E293B",
  },
  statLabel: {
    fontSize: 12,
    color: "#64748B",
    marginTop: 4,
  },
});