/**
 * Teacher Dashboard - Entry Creation System
 *
 * Generated by: Claude Opus 4.1 (claude-opus-4-1-20250805)
 * Date: October 2024
 *
 * PROMPT USED:
 * "Create a React Native teacher dashboard for a daycare app where teachers can:
 * 1. Select a class or individual children
 * 2. Choose from entry types (attendance, meals, nap, activities, etc.)
 * 3. Use a gradient background from purple to white
 * 4. Display entry types as a grid of cards with icons and colors
 * 5. Include dropdown modals for class and children selection
 * Make it modern with soft shadows, rounded corners, and smooth animations."
 *
 * DESIGN INSPIRATION: Modern daycare apps with card-based interfaces
 */

import {
  View,
  Text,
  Pressable,
  ActivityIndicator,
  ScrollView,
  StyleSheet,
  Modal,
  Alert,
} from "react-native";
import { useEffect, useMemo, useState } from "react";
import { colors } from "@/constants/color";
import { useRouter } from "expo-router";
import { collection, onSnapshot, query, where, addDoc } from "firebase/firestore";
import { db, auth } from "@/lib/firebase";
import { LinearGradient } from "expo-linear-gradient";
import { useSafeAreaInsets } from "react-native-safe-area-context";
import {
  Coffee,
  Moon,
  Apple,
  Droplet,
  FileText,
  Camera,
  Users,
  Calendar,
  Plus,
  ChevronDown,
  X,
  Check,
  Clock,
  Baby,
  Heart,
  Activity,
} from "lucide-react-native";

type Child = {
  id: string;
  name: string;
  classroomId?: string;
  status?: string;
};

type EntryType = {
  id: string;
  label: string;
  icon: any;
  color: string;
  bgColor: string;
  subtypes?: string[];
};

const entryTypes: EntryType[] = [
  {
    id: "attendance",
    label: "Attendance",
    icon: Clock,
    color: "#10B981",
    bgColor: "#D1FAE5",
    subtypes: ["Check In", "Check Out"],
  },
  {
    id: "meal",
    label: "Meal",
    icon: Apple,
    color: "#F59E0B",
    bgColor: "#FEF3C7",
    subtypes: ["Breakfast", "Lunch", "Snack"],
  },
  {
    id: "nap",
    label: "Nap Time",
    icon: Moon,
    color: "#6366F1",
    bgColor: "#E0E7FF",
    subtypes: ["Started", "Woke Up"],
  },
  {
    id: "diaper",
    label: "Diaper",
    icon: Baby,
    color: "#EC4899",
    bgColor: "#FCE7F3",
    subtypes: ["Wet", "BM", "Dry"],
  },
  {
    id: "activity",
    label: "Activity",
    icon: Activity,
    color: "#8B5CF6",
    bgColor: "#EDE9FE",
    subtypes: ["Outdoor Play", "Art & Craft", "Story Time", "Music"],
  },
  {
    id: "photo",
    label: "Photo",
    icon: Camera,
    color: "#06B6D4",
    bgColor: "#CFFAFE",
  },
  {
    id: "note",
    label: "Note",
    icon: FileText,
    color: "#64748B",
    bgColor: "#F1F5F9",
  },
  {
    id: "health",
    label: "Health",
    icon: Heart,
    color: "#EF4444",
    bgColor: "#FEE2E2",
    subtypes: ["Temperature", "Medicine", "Incident"],
  },
];

export default function TeacherDashboard() {
  const insets = useSafeAreaInsets();
  const [children, setChildren] = useState<Child[]>([]);
  const [loading, setLoading] = useState(true);
  const [selectedClass, setSelectedClass] = useState<string>("all");
  const [showClassPicker, setShowClassPicker] = useState(false);
  const [selectedChildren, setSelectedChildren] = useState<string[]>([]);
  const [showChildPicker, setShowChildPicker] = useState(false);
  const router = useRouter();

  // Live subscription to children
  useEffect(() => {
    const q = query(collection(db, "children"), where("status", "==", "enrolled"));
    const unsub = onSnapshot(
      q,
      (snap) => {
        const rows: Child[] = snap.docs.map((d) => {
          const x = d.data() as any;
          return {
            id: d.id,
            name: x.name ?? "(no name)",
            classroomId: x.classroomId,
            status: x.status,
          };
        });
        rows.sort((a, b) => a.name.localeCompare(b.name));
        setChildren(rows);
        setLoading(false);
      },
      () => {
        setChildren([]);
        setLoading(false);
      }
    );
    return () => unsub();
  }, []);

  // Get unique classrooms
  const classrooms = useMemo(() => {
    const unique = new Set<string>();
    children.forEach((c) => {
      if (c.classroomId) unique.add(c.classroomId);
    });
    return Array.from(unique).sort();
  }, [children]);

  // Filter children by selected class
  const filteredChildren = useMemo(() => {
    if (selectedClass === "all") return children;
    return children.filter((c) => c.classroomId === selectedClass);
  }, [children, selectedClass]);

  const handleEntryTypePress = async (type: EntryType) => {
    if (selectedChildren.length === 0) {
      Alert.alert("Select Children", "Please select at least one child first");
      return;
    }

    // For now, just show what would be created
    Alert.alert(
      `Create ${type.label} Entry`,
      `Would create ${type.label} entry for ${selectedChildren.length} children`,
      [
        { text: "Cancel", style: "cancel" },
        {
          text: "Create",
          onPress: async () => {
            // Here you would navigate to a detailed entry form
            // or create the entry directly
            console.log("Creating entry:", type.id, selectedChildren);
          },
        },
      ]
    );
  };

  if (loading) {
    return (
      <View style={styles.loadingContainer}>
        <ActivityIndicator size="large" color={colors.tint} />
      </View>
    );
  }

  return (
    <View style={styles.container}>
      {/* Gradient Background */}
      <LinearGradient
        colors={["#E0E7FF", "#F0F4FF", "#FFFFFF"]}
        style={styles.gradientBackground}
      />

      <ScrollView
        style={styles.scrollView}
        contentContainerStyle={{ paddingBottom: 100 }}
        showsVerticalScrollIndicator={false}
      >
        {/* Header Section */}
        <View style={[styles.header, { paddingTop: insets.top + 20 }]}>
          <Text style={styles.greeting}>Good Morning! 👋</Text>
          <Text style={styles.title}>Create Entry</Text>
        </View>

        {/* Class & Children Selection */}
        <View style={styles.selectionContainer}>
          {/* Class Selector */}
          <Pressable
            style={styles.selector}
            onPress={() => setShowClassPicker(true)}
          >
            <View style={styles.selectorIcon}>
              <Users size={20} color="#6366F1" />
            </View>
            <View style={styles.selectorContent}>
              <Text style={styles.selectorLabel}>Class</Text>
              <Text style={styles.selectorValue}>
                {selectedClass === "all" ? "All Classes" : `Class ${selectedClass}`}
              </Text>
            </View>
            <ChevronDown size={20} color="#94A3B8" />
          </Pressable>

          {/* Children Count */}
          <Pressable
            style={[styles.selector, styles.childSelector]}
            onPress={() => setShowChildPicker(true)}
          >
            <View style={[styles.selectorIcon, { backgroundColor: "#FCE7F3" }]}>
              <Baby size={20} color="#EC4899" />
            </View>
            <View style={styles.selectorContent}>
              <Text style={styles.selectorLabel}>Children</Text>
              <Text style={styles.selectorValue}>
                {selectedChildren.length === 0
                  ? "Select"
                  : selectedChildren.length === filteredChildren.length
                  ? "All Selected"
                  : `${selectedChildren.length} Selected`}
              </Text>
            </View>
            <ChevronDown size={20} color="#94A3B8" />
          </Pressable>
        </View>

        {/* Selected Children Pills */}
        {selectedChildren.length > 0 && (
          <ScrollView
            horizontal
            showsHorizontalScrollIndicator={false}
            style={styles.selectedChildrenContainer}
          >
            {selectedChildren.map((childId) => {
              const child = children.find((c) => c.id === childId);
              return (
                <View key={childId} style={styles.selectedChildPill}>
                  <Text style={styles.selectedChildName}>{child?.name}</Text>
                  <Pressable
                    onPress={() =>
                      setSelectedChildren(selectedChildren.filter((id) => id !== childId))
                    }
                  >
                    <X size={14} color="#6366F1" />
                  </Pressable>
                </View>
              );
            })}
          </ScrollView>
        )}

        {/* Entry Types Grid */}
        <View style={styles.entryTypesContainer}>
          <Text style={styles.sectionTitle}>What would you like to record?</Text>
          <View style={styles.entryGrid}>
            {entryTypes.map((type) => (
              <Pressable
                key={type.id}
                style={({ pressed }) => [
                  styles.entryCard,
                  { transform: [{ scale: pressed ? 0.95 : 1 }] },
                ]}
                onPress={() => handleEntryTypePress(type)}
              >
                <View style={[styles.entryIconContainer, { backgroundColor: type.bgColor }]}>
                  <type.icon size={24} color={type.color} strokeWidth={2} />
                </View>
                <Text style={styles.entryLabel}>{type.label}</Text>
                {type.subtypes && (
                  <Text style={styles.entrySubtypes}>{type.subtypes.length} options</Text>
                )}
              </Pressable>
            ))}
          </View>
        </View>

        {/* Quick Actions */}
        <View style={styles.quickActionsContainer}>
          <Text style={styles.sectionTitle}>Quick Actions</Text>
          <Pressable style={styles.quickAction}>
            <View style={styles.quickActionIcon}>
              <Calendar size={20} color="#10B981" />
            </View>
            <Text style={styles.quickActionText}>Today's Schedule</Text>
            <ChevronDown size={18} color="#94A3B8" style={{ transform: [{ rotate: '-90deg' }] }} />
          </Pressable>
          <Pressable style={styles.quickAction}>
            <View style={styles.quickActionIcon}>
              <FileText size={20} color="#F59E0B" />
            </View>
            <Text style={styles.quickActionText}>View Reports</Text>
            <ChevronDown size={18} color="#94A3B8" style={{ transform: [{ rotate: '-90deg' }] }} />
          </Pressable>
        </View>
      </ScrollView>

      {/* Class Picker Modal */}
      <Modal visible={showClassPicker} transparent animationType="slide">
        <Pressable style={styles.modalOverlay} onPress={() => setShowClassPicker(false)}>
          <View style={styles.modalContent}>
            <Text style={styles.modalTitle}>Select Class</Text>
            <Pressable
              style={styles.modalOption}
              onPress={() => {
                setSelectedClass("all");
                setShowClassPicker(false);
              }}
            >
              <Text style={styles.modalOptionText}>All Classes</Text>
              {selectedClass === "all" && <Check size={20} color="#6366F1" />}
            </Pressable>
            {classrooms.map((classId) => (
              <Pressable
                key={classId}
                style={styles.modalOption}
                onPress={() => {
                  setSelectedClass(classId);
                  setShowClassPicker(false);
                }}
              >
                <Text style={styles.modalOptionText}>Class {classId}</Text>
                {selectedClass === classId && <Check size={20} color="#6366F1" />}
              </Pressable>
            ))}
          </View>
        </Pressable>
      </Modal>

      {/* Children Picker Modal */}
      <Modal visible={showChildPicker} transparent animationType="slide">
        <Pressable style={styles.modalOverlay} onPress={() => setShowChildPicker(false)}>
          <View style={styles.modalContent}>
            <View style={styles.modalHeader}>
              <Text style={styles.modalTitle}>Select Children</Text>
              <Pressable
                onPress={() => {
                  if (selectedChildren.length === filteredChildren.length) {
                    setSelectedChildren([]);
                  } else {
                    setSelectedChildren(filteredChildren.map((c) => c.id));
                  }
                }}
              >
                <Text style={styles.selectAllText}>
                  {selectedChildren.length === filteredChildren.length ? "Deselect All" : "Select All"}
                </Text>
              </Pressable>
            </View>
            <ScrollView style={styles.childrenList}>
              {filteredChildren.map((child) => (
                <Pressable
                  key={child.id}
                  style={styles.modalOption}
                  onPress={() => {
                    if (selectedChildren.includes(child.id)) {
                      setSelectedChildren(selectedChildren.filter((id) => id !== child.id));
                    } else {
                      setSelectedChildren([...selectedChildren, child.id]);
                    }
                  }}
                >
                  <Text style={styles.modalOptionText}>{child.name}</Text>
                  {selectedChildren.includes(child.id) && <Check size={20} color="#6366F1" />}
                </Pressable>
              ))}
            </ScrollView>
            <Pressable
              style={styles.doneButton}
              onPress={() => setShowChildPicker(false)}
            >
              <Text style={styles.doneButtonText}>Done</Text>
            </Pressable>
          </View>
        </Pressable>
      </Modal>
    </View>
  );
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#FFFFFF",
  },
  gradientBackground: {
    position: "absolute",
    top: 0,
    left: 0,
    right: 0,
    height: 400,
  },
  scrollView: {
    flex: 1,
  },
  loadingContainer: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
  },
  header: {
    paddingHorizontal: 20,
    marginBottom: 24,
  },
  greeting: {
    fontSize: 16,
    color: "#64748B",
    marginBottom: 4,
  },
  title: {
    fontSize: 32,
    fontWeight: "bold",
    color: "#1E293B",
    letterSpacing: -0.5,
  },
  selectionContainer: {
    paddingHorizontal: 20,
    marginBottom: 16,
  },
  selector: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#FFFFFF",
    borderRadius: 12,
    padding: 12,
    marginBottom: 12,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.05,
    shadowRadius: 8,
    elevation: 2,
  },
  childSelector: {
    marginBottom: 0,
  },
  selectorIcon: {
    width: 36,
    height: 36,
    borderRadius: 10,
    backgroundColor: "#E0E7FF",
    alignItems: "center",
    justifyContent: "center",
    marginRight: 12,
  },
  selectorContent: {
    flex: 1,
  },
  selectorLabel: {
    fontSize: 12,
    color: "#94A3B8",
    marginBottom: 2,
  },
  selectorValue: {
    fontSize: 15,
    fontWeight: "600",
    color: "#1E293B",
  },
  selectedChildrenContainer: {
    paddingHorizontal: 20,
    marginBottom: 20,
    maxHeight: 40,
  },
  selectedChildPill: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#E0E7FF",
    borderRadius: 20,
    paddingHorizontal: 12,
    paddingVertical: 6,
    marginRight: 8,
  },
  selectedChildName: {
    fontSize: 13,
    color: "#6366F1",
    fontWeight: "500",
    marginRight: 6,
  },
  entryTypesContainer: {
    paddingHorizontal: 20,
    marginBottom: 32,
  },
  sectionTitle: {
    fontSize: 18,
    fontWeight: "600",
    color: "#1E293B",
    marginBottom: 16,
  },
  entryGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    marginHorizontal: -6,
  },
  entryCard: {
    width: "31%",
    backgroundColor: "#FFFFFF",
    borderRadius: 16,
    padding: 16,
    margin: "1.16%",
    alignItems: "center",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.05,
    shadowRadius: 8,
    elevation: 2,
  },
  entryIconContainer: {
    width: 48,
    height: 48,
    borderRadius: 12,
    alignItems: "center",
    justifyContent: "center",
    marginBottom: 8,
  },
  entryLabel: {
    fontSize: 13,
    fontWeight: "600",
    color: "#1E293B",
    textAlign: "center",
  },
  entrySubtypes: {
    fontSize: 11,
    color: "#94A3B8",
    marginTop: 2,
  },
  quickActionsContainer: {
    paddingHorizontal: 20,
    marginBottom: 32,
  },
  quickAction: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#FFFFFF",
    borderRadius: 12,
    padding: 16,
    marginBottom: 12,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.05,
    shadowRadius: 8,
    elevation: 2,
  },
  quickActionIcon: {
    width: 36,
    height: 36,
    borderRadius: 10,
    backgroundColor: "#F0FDF4",
    alignItems: "center",
    justifyContent: "center",
    marginRight: 12,
  },
  quickActionText: {
    flex: 1,
    fontSize: 15,
    fontWeight: "500",
    color: "#1E293B",
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: "rgba(0, 0, 0, 0.5)",
    justifyContent: "flex-end",
  },
  modalContent: {
    backgroundColor: "#FFFFFF",
    borderTopLeftRadius: 24,
    borderTopRightRadius: 24,
    padding: 20,
    maxHeight: "50%",
  },
  modalHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 16,
  },
  modalTitle: {
    fontSize: 18,
    fontWeight: "600",
    color: "#1E293B",
  },
  selectAllText: {
    fontSize: 14,
    color: "#6366F1",
    fontWeight: "500",
  },
  modalOption: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    paddingVertical: 12,
    borderBottomWidth: 1,
    borderBottomColor: "#F1F5F9",
  },
  modalOptionText: {
    fontSize: 15,
    color: "#1E293B",
  },
  childrenList: {
    maxHeight: 300,
  },
  doneButton: {
    backgroundColor: "#6366F1",
    borderRadius: 12,
    padding: 14,
    alignItems: "center",
    marginTop: 16,
  },
  doneButtonText: {
    color: "#FFFFFF",
    fontSize: 16,
    fontWeight: "600",
  },
});