/**
 * AI-Generated Code Citation
 * Generated by: Claude Code (Anthropic)
 * Prompt: "Redesign login page with split-screen layout, form validation, and comprehensive debug logging"
 * Date: 2025-09-30
 */

// app/login/page.tsx
'use client';

import { useEffect, useMemo, useState,  } from 'react';
import Link from 'next/link';
import { useRouter } from 'next/navigation';
import Image from 'next/image';
import { useAuth } from '@/lib/auth';
import Cookies from 'js-cookie';


export default function LoginPage() {
  const { signIn, currentUser, loading } = useAuth();
  const router = useRouter();

  const [email, setEmail] = useState('');
  const [pw, setPw] = useState('');
  const [err, setErr] = useState<string | null>(null);
  const [showPassword, setShowPassword] = useState(false);


  console.log('[Login Page] Component state:', { email, loading, hasError: !!err });

  const valid = useMemo(() => {
    const okEmail = /^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email.trim());
    const isValid = okEmail && pw.length >= 6 && pw.length <= 50 && pw.trim() === pw;
    console.log('[Login Page] Form validation:', { okEmail, pwLength: pw.length, isValid });
    return isValid;
  }, [email, pw]);

  const onSubmit = async (e: React.FormEvent<HTMLFormElement>) => {
    e.preventDefault();
    if (!valid || loading) {
      return;
    }

    try {
      setErr(null);
      await signIn(email.trim().toLowerCase(), pw);
      // If success, direct user to the entrance page: app/page.tsx
      router.replace('/');
      
    } catch (e: unknown) {
      const message = e instanceof Error ? e.message : 'Login failed';
      setErr(message);
    } finally {
    }
  };
  return (
    <div className="flex min-h-screen">
      {/* Left Side - Hero Section */}
      <div className="hidden lg:flex lg:w-1/2 bg-gradient-to-br from-gray-900 via-gray-800 to-gray-900 relative overflow-hidden">
        <div className="flex flex-col items-center justify-center w-full h-full text-center px-12 relative z-10">
          {/* Large logo */}
          <div className="mb-8">
            <Image
              src="/logo.svg"
              alt="Sunshine"
              width={160}
              height={160}
              className="brightness-0 invert"
            />
          </div>

          {/* Brand name */}
          <h1 className="text-4xl font-bold text-white mb-4">
            Sunshine Daycare
          </h1>

          {/* Tagline */}
          <p className="text-xl text-gray-300 mb-12 max-w-md">
            Modern management for modern daycares
          </p>

          {/* Feature list */}
          <div className="space-y-4 text-left max-w-sm">
            <Feature icon="✓" text="Streamline teacher scheduling" />
            <Feature icon="✓" text="Real-time parent communication" />
            <Feature icon="✓" text="Effortless class management" />
            <Feature icon="✓" text="Secure and compliant" />
          </div>
        </div>
      </div>

      {/* Right Side - Auth Form */}
      <div className="w-full lg:w-1/2 flex items-center justify-center px-6 py-12 bg-white">
        <div className="w-full max-w-[400px]">
          {/* Small logo for mobile/tablet */}
          <div className="flex justify-center mb-8">
            <Image
              src="/logo.svg"
              alt="Sunshine"
              width={40}
              height={40}
            />
          </div>

          {/* Heading */}
          <div className="mb-8">
            <h2 className="text-3xl font-bold text-gray-900 mb-2">
              Welcome back
            </h2>
            <p className="text-sm text-gray-600">
              Sign in to your account
            </p>
          </div>

          {/* Form */}
          <form onSubmit={onSubmit} className="space-y-5">
            {/* Email */}
            <div>
              <label htmlFor="email" className="block text-sm font-medium text-gray-700 mb-1.5">
                Email address
              </label>
              <input
                id="email"
                type="email"
                value={email}
                onChange={(e) => setEmail(e.currentTarget.value)}
                className={`w-full h-11 px-3 text-base rounded-lg border ${
                  err ? 'border-red-500 focus:border-red-500 focus:ring-red-500' : 'border-gray-300 focus:border-gray-900 focus:ring-gray-900'
                } focus:ring-2 focus:ring-offset-0 focus:outline-none transition-all duration-200 placeholder:text-gray-400`}
                placeholder="you@example.com"
                autoComplete="email"
                required
                disabled={loading}
                aria-describedby={err ? 'error-message' : undefined}
              />
            </div>

            {/* Password */}
            <div>
              <label htmlFor="password" className="block text-sm font-medium text-gray-700 mb-1.5">
                Password
              </label>
              <div className="relative">
                <input
                  id="password"
                  type={showPassword ? 'text' : 'password'}
                  value={pw}
                  onChange={(e) => setPw(e.currentTarget.value)}
                  className={`w-full h-11 px-3 pr-10 text-base rounded-lg border ${
                    err ? 'border-red-500 focus:border-red-500 focus:ring-red-500' : 'border-gray-300 focus:border-gray-900 focus:ring-gray-900'
                  } focus:ring-2 focus:ring-offset-0 focus:outline-none transition-all duration-200 placeholder:text-gray-400`}
                  placeholder="••••••••"
                  autoComplete="current-password"
                  required
                  disabled={loading}
                  aria-describedby={err ? 'error-message' : undefined}
                />
                <button
                  type="button"
                  onClick={() => setShowPassword(!showPassword)}
                  className="absolute right-3 top-1/2 -translate-y-1/2 text-gray-400 hover:text-gray-600 transition-colors duration-200"
                  aria-label={showPassword ? 'Hide password' : 'Show password'}
                >
                  {showPassword ? (
                    <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" strokeWidth={1.5} stroke="currentColor" className="w-5 h-5">
                      <path strokeLinecap="round" strokeLinejoin="round" d="M3.98 8.223A10.477 10.477 0 001.934 12C3.226 16.338 7.244 19.5 12 19.5c.993 0 1.953-.138 2.863-.395M6.228 6.228A10.45 10.45 0 0112 4.5c4.756 0 8.773 3.162 10.065 7.498a10.523 10.523 0 01-4.293 5.774M6.228 6.228L3 3m3.228 3.228l3.65 3.65m7.894 7.894L21 21m-3.228-3.228l-3.65-3.65m0 0a3 3 0 10-4.243-4.243m4.242 4.242L9.88 9.88" />
                    </svg>
                  ) : (
                    <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" strokeWidth={1.5} stroke="currentColor" className="w-5 h-5">
                      <path strokeLinecap="round" strokeLinejoin="round" d="M2.036 12.322a1.012 1.012 0 010-.639C3.423 7.51 7.36 4.5 12 4.5c4.638 0 8.573 3.007 9.963 7.178.07.207.07.431 0 .639C20.577 16.49 16.64 19.5 12 19.5c-4.638 0-8.573-3.007-9.963-7.178z" />
                      <path strokeLinecap="round" strokeLinejoin="round" d="M15 12a3 3 0 11-6 0 3 3 0 016 0z" />
                    </svg>
                  )}
                </button>
              </div>
            </div>

            {/* Error message */}
            {err && (
              <div
                id="error-message"
                role="alert"
                className="bg-red-50 border border-red-200 text-red-800 px-3 py-3 rounded-lg flex items-start gap-2 text-sm animate-in fade-in duration-200"
              >
                <span className="text-base leading-none">⚠️</span>
                <span className="flex-1">{err}</span>
              </div>
            )}

            {/* Submit button */}
            <button
              type="submit"
              disabled={!valid || loading}
              className={`w-full h-11 font-semibold rounded-lg transition-all duration-200 mt-6 ${
                valid && !loading
                  ? 'bg-gray-900 hover:bg-gray-800 text-white cursor-pointer'
                  : 'bg-gray-300 text-gray-500 cursor-not-allowed'
              }`}
            >
              {loading ? 'Signing in...' : 'Sign in'}
            </button>
          </form>

          {/* Link to signup */}
          <p className="mt-6 text-center text-sm text-gray-600">
            Don&apos;t have an account?{' '}
            <Link href="/signup" className="text-gray-900 underline hover:text-gray-600 transition-colors duration-200">
              Create account
            </Link>
          </p>
        </div>
      </div>
    </div>
  );
}

function Feature({ icon, text }: { icon: string; text: string }) {
  return (
    <div className="flex items-center gap-3 text-white">
      <span className="text-green-400 text-xl font-bold">{icon}</span>
      <span className="text-gray-200">{text}</span>
    </div>
  );
}